[workspace]
members = [
    "core",
    "config",
    "admin/api",
    "admin/web",
    "cli",
    "grpc/sink_hub",
    "grpc/link_hub",
    "grpc/hub_sink",
    "grpc/hub_link",
    "demo/grpc_hub",
    "demo/echo_sink",
    "demo/echo_link",
]
